CREATE TABLE IF NOT EXISTS refresh_tokens
(
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     UUID          NOT NULL,
    token       VARCHAR(1024) NOT NULL,
    expiry_date TIMESTAMP     NOT NULL,
    created_at  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    revoked     BOOLEAN       NOT NULL,
    revoked_at  TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

